PC ?= pc

APPLICATION := feconf_protocol
DESCRIPTION := FECONF protocol generated by the protocol compiler
VSN := 1.0
MODULES := feconfv1_protocol
INCL_TARGETS := feconfv1_protocol.hrl

include ${ERL_LIBS}/erlang.mk

FECONFv1.proto ::
	@echo Downloading latest version of $@...; \
	curl -Rso $@ 'https://www-bd.fnal.gov/cgi-cvs/cvsweb.cgi/~checkout~/mecca/uls/ul_feconf_protocol/$@?rev=HEAD;content-type=text%2Fplain'

feconfv1_protocol.erl feconfv1_protocol.hrl : FECONFv1.proto
	${PC} -l erlang --erl-bin-str $^

feconfv1_protocol.beam : feconfv1_protocol.hrl

clean ::
	rm -f feconfv1_protocol.erl feconfv1_protocol.hrl
